# Generated by Django 6.1 on 2026-08-21 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.turn'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('name', 'area')},
        ),
    ]
