# Generated by Django 6.1 on 2026-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha del Festivo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre / Motivo')),
            ],
            options={
                'verbose_name': 'Festivo Personalizado',
                'verbose_name_plural': 'Festivos Personalizados',
                'ordering': ['date'],
            },
        ),
    ]
