# Generated by Django 6.1 on 2026-08-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_customholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeturn',
            options={'verbose_name': 'Matriz de Turno', 'verbose_name_plural': 'Matrices de Turnos'},
        ),
        migrations.RemoveField(
            model_name='employeeturn',
            name='turn',
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn_friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.turn'),
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn_monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.turn'),
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn_saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.turn'),
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn_sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.turn'),
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn_thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.turn'),
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn_tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.turn'),
        ),
        migrations.AddField(
            model_name='employeeturn',
            name='turn_wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.turn'),
        ),
        migrations.AlterField(
            model_name='employeeturn',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio Asignación'),
        ),
    ]
