# Generated by Django 6.1 on 2026-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_employeeturn_options_remove_employeeturn_turn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, default=6.195, max_digits=10, verbose_name='Latitud Empresa')),
                ('longitude', models.DecimalField(decimal_places=7, default=-75.5685, max_digits=10, verbose_name='Longitud Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
    ]
