# Generated by Django 6.1 on 2026-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='tolerance_radius',
            field=models.IntegerField(default=30, verbose_name='Radio de Tolerancia (m)'),
        ),
    ]
