# Generated by Django 6.1 on 2026-08-21 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador Global'), ('JEFE', 'Jefe Inmediato'), ('COLABORADOR', 'Colaborador')], default='COLABORADOR', max_length=20, verbose_name='Rol/Perfil')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='secure/signatures/', verbose_name='Firma Digital')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Contacto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Contacto de Emergencia')),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, verbose_name='Número Contacto Emergencia')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.area', verbose_name='Área')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Jefe Inmediato')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.position', verbose_name='Cargo')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario / Colaborador',
                'verbose_name_plural': 'Usuarios / Colaboradores',
            },
        ),
    ]
