# Generated by Django 6.1 on 2026-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('severity', models.CharField(choices=[('LEVE', 'Leve'), ('GRAVE', 'Grave'), ('MUY_GRAVE', 'Muy grave')], max_length=20, verbose_name='Tipo de Falta')),
                ('description', models.TextField(verbose_name='Descripción Detallada del Hecho')),
                ('employee_defense', models.TextField(blank=True, verbose_name='Descargos del Colaborador')),
                ('decision', models.CharField(default='Llamado de atención escrito', max_length=100, verbose_name='Decisión')),
                ('employee_signature', models.ImageField(blank=True, null=True, upload_to='secure/acts/employee_signatures/', verbose_name='Firma del Colaborador')),
                ('manager_signature', models.ImageField(blank=True, null=True, upload_to='secure/acts/manager_signatures/', verbose_name='Firma del Jefe Inmediato')),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='secure/acts/documents/', verbose_name='Acta en PDF')),
            ],
            options={
                'verbose_name': 'Acta Disciplinaria',
                'verbose_name_plural': 'Actas Disciplinarias',
            },
        ),
        migrations.CreateModel(
            name='PayrollSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mes de Pago')),
                ('document', models.FileField(upload_to='secure/payroll/', verbose_name='Colilla de Nómina')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
            ],
            options={
                'verbose_name': 'Colilla de Nómina',
                'verbose_name_plural': 'Colillas de Nómina',
            },
        ),
    ]
