# Generated by Django 6.1 on 2026-09-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio (Salida)')),
                ('end_date', models.DateField(verbose_name='Fecha Final')),
                ('return_date', models.DateField(verbose_name='Fecha de Regreso a Labores')),
                ('days_enjoyed', models.PositiveIntegerField(verbose_name='Días Hábiles a Disfrutar')),
                ('employee_signature', models.ImageField(blank=True, null=True, upload_to='secure/vacations/employee_signatures/', verbose_name='Firma del Colaborador')),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='secure/vacations/documents/', verbose_name='Notificación en PDF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Vacaciones',
                'verbose_name_plural': 'Notificaciones de Vacaciones',
            },
        ),
    ]
