# Generated by Django 6.1 on 2026-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_vacationnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationnotification',
            name='manager_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Jefe/Admin'),
        ),
        migrations.AddField(
            model_name='vacationnotification',
            name='manager_signature',
            field=models.ImageField(blank=True, null=True, upload_to='secure/vacations/manager_signatures/', verbose_name='Firma del Jefe/Admin'),
        ),
    ]
