# Generated by Django 6.1 on 2026-08-21 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Marcación')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Ingreso')),
                ('entry_status', models.CharField(blank=True, choices=[('A_TIEMPO', 'A Tiempo'), ('RETARDO', 'Retardo'), ('FALTA', 'Falta')], max_length=20, null=True, verbose_name='Estado de Ingreso')),
                ('entry_photo', models.ImageField(blank=True, null=True, upload_to='attendance/entry/', verbose_name='Foto de Ingreso')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('exit_photo', models.ImageField(blank=True, null=True, upload_to='attendance/exit/', verbose_name='Foto de Salida')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Trabajadas')),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Extras')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CITA_MEDICA', 'Cita médica (Remunerado)'), ('ELECCIONES', 'Elecciones / Jurado (Remunerado)'), ('CALAMIDAD', 'Calamidad (Remunerado)'), ('ESCOLARES', 'Obligaciones escolares (Remunerado)'), ('JUDICIALES', 'Citas Judiciales (Remunerado)'), ('LUTO', 'Luto (Remunerado)'), ('ENFERMEDAD', 'Enfermedad General (Remunerado)'), ('PERSONALES', 'Asuntos personales (NO Remunerado)'), ('OTROS', 'Otros (Descuenta tiempo)'), ('VACACIONES', 'Vacaciones')], max_length=30, verbose_name='Categoría de Permiso')),
                ('start_date', models.DateTimeField(verbose_name='Fecha/Hora Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha/Hora Fin')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación/Rechazo')),
                ('admin_observations', models.TextField(blank=True, verbose_name='Observaciones del Administrador')),
            ],
            options={
                'verbose_name': 'Permiso / Vacaciones',
                'verbose_name_plural': 'Permisos / Vacaciones',
            },
        ),
    ]
