# Generated by Django 6.1 on 2026-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='justification_type',
            field=models.CharField(choices=[('NORMAL', 'Ninguna / Normal'), ('REMUNERADO', 'Permisos Remunerados'), ('NO_REMUNERADO', 'Permisos No Remunerados')], default='NORMAL', max_length=20, verbose_name='Tipo de Justificación'),
        ),
    ]
