# Generated by Django 6.1 on 2026-08-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_justification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='justification_type',
            field=models.CharField(choices=[('NORMAL', 'Ninguna / Normal'), ('CITA_MEDICA', 'Permiso remunerado: Cita médica'), ('ELECCIONES', 'Permiso remunerado: Elecciones / Jurado'), ('CALAMIDAD', 'Permiso remunerado: Calamidad'), ('ESCOLAR', 'Permiso remunerado: Obligaciones escolares'), ('JUDICIAL', 'Permiso remunerado: Citas Judiciales'), ('LUTO', 'Permiso remunerado: Luto'), ('ENFERMEDAD', 'Permiso remunerado: Enfermedad General'), ('PERSONAL', 'Permiso NO Remunerado: Asuntos personales'), ('OTROS', 'Permiso NO Remunerado: Otros')], default='NORMAL', max_length=20, verbose_name='Tipo de Justificación'),
        ),
    ]
