# Generated by Django 6.1 on 2026-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_justification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_out_of_bounds',
            field=models.BooleanField(default=False, verbose_name='Fuera de Rango (30m)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
