# Generated by Django 6.1 on 2026-08-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_is_out_of_bounds_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='days_requested',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días a disfrutar'),
        ),
    ]
