# Generated by Django 6.1 on 2026-08-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_permission_days_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='permission_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas de Permiso (Salida Temprano)'),
        ),
    ]
