# Generated by Django 6.1 on 2026-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_permission_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='justification_type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='entry_justification',
            field=models.CharField(choices=[('NORMAL', 'Ninguna / Normal'), ('CITA_MEDICA', 'Permiso remunerado: Cita médica'), ('ELECCIONES', 'Permiso remunerado: Elecciones / Jurado'), ('CALAMIDAD', 'Permiso remunerado: Calamidad'), ('ESCOLAR', 'Permiso remunerado: Obligaciones escolares'), ('JUDICIAL', 'Permiso remunerado: Citas Judiciales'), ('LUTO', 'Permiso remunerado: Luto'), ('ENFERMEDAD', 'Permiso remunerado: Enfermedad General'), ('PERSONAL', 'Permiso NO Remunerado: Asuntos personales'), ('OTROS', 'Permiso NO Remunerado: Otros')], default='NORMAL', max_length=20, verbose_name='Justificación Ingreso'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='entry_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones Ingreso'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='exit_justification',
            field=models.CharField(choices=[('NORMAL', 'Ninguna / Normal'), ('CITA_MEDICA', 'Permiso remunerado: Cita médica'), ('ELECCIONES', 'Permiso remunerado: Elecciones / Jurado'), ('CALAMIDAD', 'Permiso remunerado: Calamidad'), ('ESCOLAR', 'Permiso remunerado: Obligaciones escolares'), ('JUDICIAL', 'Permiso remunerado: Citas Judiciales'), ('LUTO', 'Permiso remunerado: Luto'), ('ENFERMEDAD', 'Permiso remunerado: Enfermedad General'), ('PERSONAL', 'Permiso NO Remunerado: Asuntos personales'), ('OTROS', 'Permiso NO Remunerado: Otros')], default='NORMAL', max_length=20, verbose_name='Justificación Salida'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='exit_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones Salida'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones Generales'),
        ),
    ]
